# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-13 03:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20180112_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='music.Question'),
            preserve_default=False,
        ),
    ]
