# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-15 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='person',
            field=models.CharField(default=b'0000000', max_length=40),
        ),
    ]
