# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-15 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_question_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='person',
            field=models.CharField(max_length=40),
        ),
    ]
