# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-16 17:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_auto_20180116_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='question',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='music.Question'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='person',
            field=models.CharField(max_length=50),
        ),
    ]
