# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-16 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_auto_20180116_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Question'),
        ),
    ]
